config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'channels#index'
  get '/types/:object_type', to: 'channels#index'
  resources :channels
  resources :items 
  resources :votes
  get '/users', to: 'users#show'
  resources :users, only: [:show, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :items
  belongs_to :user

  def self.default_scope 
    includes(items: :votes).order('votes.created_at desc')
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :channel
  has_many :votes
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :votes
  has_many :channels
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :item
  belongs_to :user
  default_scope { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  helper_method :object_type

  def object_type
    params[:object_type]
  end

  def object_type_filter
    object_type ? {object_type: object_type} : nil
  end 

  def channel_params
    params.require(:channel).permit(:name, :description, :object_type, :user_id)
  end

  def index

    if (object_type) 
      @channels = Channel.where(object_type_filter)
        .group_by(&:object_type)
      @votes = Vote.includes(:user, item:[:channel]).where(channels: object_type_filter)
    else
      @channels = Channel.limit(50)
        .group_by(&:object_type)
      @votes = Vote
        .includes(:user, item: [:channel])
    end
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    @channel.user_id = current_user.id

    respond_to do |format|
      
      if @channel.save
        format.html { redirect_back fallback_location: '/', notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @Channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @channel = Channel.find(params[:id])

    @channels = Channel.where(object_type: @channel.object_type).where.not(id: @channel.id).limit(50)
    # .items.sort_by {|obj| -obj[:votes_count]}

    @votes = Vote.includes(item:[:channel]).where(items:{channel_id: params[:id]})
        .limit(50)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create

    ActiveRecord::Base.transaction do
      # create the item
      @item = Item.new(item_params)
      @item.votes_count = 1
      @item.save!

      # save the event in the log
      @vote = Vote.new({item_id: @item.id, user_id: current_user.id, new_item: true})
      @vote.save!
    end

    respond_to do |format|
      format.html { redirect_back fallback_location: '/', notice: "Item was successfully created." }
      format.json { render :show, status: :created, location: @item }
    end

    rescue ActiveRecord::RecordInvalid 
      respond_to do |format|
        format.html { redirect_back fallback_location: '/', notice: "Error while saving the item"}
        format.json { render status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :url, :channel_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :object_type
  def object_type
    params[:object_type]
  end

  def object_type_filter
    object_type ? {object_type: object_type} : nil
  end 

  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
    @channels = Channel.includes(:items).where({user_id: @user.id}).where(object_type_filter)
    puts @channels
    @channel = Channel.new
    @votes = Vote.where(user_id: @user.id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @item = Item.find(item_params[:item_id])

    if (!Vote.where(item_id: @item.id, user_id: current_user.id).empty?) 
      respond_to do |format|
        error = "You already voted for this #{@item.channel.object_type}"
        format.html { redirect_back fallback_location: '/', notice: error }
        format.json { render json: error, status: :unprocessable_entity }
      end

    else
      ActiveRecord::Base.transaction do
        @vote = Vote.new(item_params)
        @vote.new_item = false
        @vote.user_id = current_user.id
        @vote.save!

        @item.votes_count = @item.votes_count + 1
        @item.save!
      end

      respond_to do |format|
        format.html { redirect_back fallback_location: '/', notice: "Vote was successfully cast." }
        format.json { render :show, status: :created, location: @vote }
      end
    end

    rescue ActiveRecord::RecordInvalid
      respond_to do |format|
        format.html { redirect_back fallback_location: '/', notice: "Error while saving the item"}
        format.json { render status: :unprocessable_entity }
      end 
  end

  def item_params
    params.require(:vote).permit(:item_id)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def get_items(channel, condensed_view) 
    items = channel.items.sort_by {|obj| -obj[:votes_count]}
    if condensed_view
      items.take(5)
    else
      items
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/channels/_channel.html.erb
    <div class='channel'>
      <div class="channel-icons">
        <% if condensed_view %>
          <%= link_to "↗", channel_path(channel, {context: request.path})%>
        <% else %>
          <%= link_to "↙", request.params[:context] %>
        <% end %>

      </div>
      <% if condensed_view %>
        <h2>
          <%= channel.name %> 
          (<a href="/types/<%=channel.object_type%>"><%=channel.object_type.pluralize %></a>)
          <span class="description"><%= channel.description %></span>
        </h2>
      <% else %>
        <h1>
          <%= channel.name %> 
          (<a href="/types/<%=channel.object_type%>"><%=channel.object_type.pluralize %></a>)
          <span class="description"><%= channel.description %></span>
        </h1>
      <% end %>

      <% if channel.items.empty? %>
          <div class="message">List empty</div>
      <% else %>
        <ul>
          <% get_items(channel, condensed_view).each do |item| %>
            <li> 
              <%= form_with(model: item.votes.build , url: { :action => "create", :controller => "votes" }, local: true ) do |form| %>
                <%= form.hidden_field :item_id, :value => item.id %>
                <%= form.submit 'Vote' %>
              <% end %>

              <%if item.url.empty? %>
                <%= item.name %>
              <% else %>
                <a href="<%=item.url%>" target="_blank"> <%= item.name %></a> 
              <% end %>

              <span class="description item-votes"><%=item.votes_count%></span>
            </li>
          <% end %>
        </ul>
      <% end %>


      <% if condensed_view %>
        <div class="channel-actions">
          <%= link_to "Expand", channel %>
        </div>
      <% else %>
        <div class='channel-actions'>
          <%= form_with(model: @channel.items.build , url: { :action => "create", :controller => "items" }, local: true ) do |form| %>
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, {autofocus: true} %>

              <%= form.label :url %>
              <%= form.text_field :url %>
              <%= form.hidden_field :channel_id, :value => @channel.id %>
              <%= form.submit "add #{channel.object_type}" %>
            </div>
          <% end %>
        </div>
      <%end%>
    </div>

app/views/channels/index.html.erb
<% @channels.each_pair do |type, channels| %>

  <h1><%=type%> lists 
    <% if @channels.length == 1 %>
    (<a href="/">see all lists</a>)
    <% else %>
    (<a href="/types/<%=type%>/">see all </a>)
    <% end %>
  </h1>
  <div class='channels'>
    <%= render channels, condensed_view: true %>
  </div>
<% end %>

<% if @channels.empty? %> 
    <div class="message">No <%= object_type %> lists. Create a new one or <a href="/">See all channels</a> </div>
  <% else %>
<% end %>

<% if current_user %>
  <div class="message"><a href="/users">Go to your profile</a> to create a new list</a> </div>
<% else %>
  <div class="message"><a href="/sign_in">Sign in</a> to create a new list</a> </div>
<% end %>

<ul class='votes'>
  <%= render @votes %>
</ul>

app/views/channels/show.html.erb
  <%= render @channel, condensed_view: false %>

  <ul class='votes'>
    <%= render @votes %>
  </ul>

  <h2> Other <%=@channel.object_type %> lists</h2>
  <div class='channels'>
    <%= render @channels, condensed_view: true %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="header">
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
    </div>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>


    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%=@user.email%></h1>
<% if @channels.empty? %> 
  <div class="message">No lists.</div>
<% end %>

<div class='channels'>
  <%= render @channels, condensed_view: true %>
  <% if @user == current_user %>
    <div class='channel long-form'>
      <h2>Your new List </h2>
      <%= form_with(model: @channel, local: true) do |form| %>
        <% if @channel.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this item from being saved:</h2>
            <ul>
              <% @channel.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>
        <div class="field">
          <%= form.label :description %>
          <%= form.text_field :description %>
        </div>
        <% if object_type %>
          <%= form.hidden_field :object_type, :value => object_type%>
        <% else %>
          <div class="field">
            <%= form.label :object_type %>
            <%= form.text_field :object_type %>
          </div>
        <% end %>
        <div class="channel-actions">
          <%= form.submit "Add list" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>


<ul class='votes'>
  <%= render @votes %>
</ul>

app/views/votes/_vote.html.erb
<li>
        <a href="/users/<%=vote.user.id%>">
          <b><%= vote.user.email %></b>
        </a>
        <%= vote.new_item ? ' added ' : ' upvoted ' %>
        <b><%= vote.item.name %></b>
        in
        <a href="/channels/<%=vote.item.channel_id%>">
          <b><%= vote.item.channel.name %></b>
          <b><%= vote.item.channel.object_type %></b>
        </a>
</li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>